# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/pictures')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('reservation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='static/pictures')),
                ('kind', models.IntegerField(choices=[(1, 'hala wielofukcyjna'), (2, 'boisko piłkarskie'), (3, 'pływalnia'), (4, 'obiekt lekkoatletyczny')])),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('sports', models.IntegerField(choices=[(1, 'piłka nożna'), (2, 'koszykówka'), (3, 'siatkówka'), (4, 'tenis'), (5, 'futsal'), (6, 'pływanie'), (7, 'piłka wodna'), (8, 'biegi'), (9, 'rzuty'), (10, 'skoki')])),
                ('rating', models.IntegerField(choices=[(1, 'obiekt bez wyposażenia'), (2, 'komplet przyrządów sportowych do obsługiwanych dyscyplin'), (3, 'klimatyzacja / sztuczne oświetlenie')], default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportchallenger.SportFacility'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportchallenger.MyUser'),
        ),
    ]
