# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportchallenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
